apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3  # The number of instances you want
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: faridadwanii/python-jenkins-app  # Replace with your Docker image
        ports:
        - containerPort: 80  # Replace with the port your app listens on
